-- Seed Rotaract District 2451 clubs.
-- Run in the Supabase Dashboard > SQL Editor.
-- Safe to re-run: inserts are keyed by the unique club slug (ON CONFLICT DO NOTHING).

INSERT INTO clubs (name, slug, city, university, country, is_active) VALUES
  ('Rotaract Cairo North', 'rotaract-cairo-north', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract ESLSCA Cairo Rally', 'rotaract-eslsca-cairo-rally', 'Cairo', 'ESLSCA', 'Egypt', TRUE),
  ('Rotaract The British University', 'rotaract-the-british-university', 'Cairo', 'The British University in Egypt', 'Egypt', TRUE),
  ('Rotaract Cairo West', 'rotaract-cairo-west', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Giza Metropolitan', 'rotaract-giza-metropolitan', 'Giza', NULL, 'Egypt', TRUE),
  ('Rotaract Cairo New Capital', 'rotaract-cairo-new-capital', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract El Maadi', 'rotaract-el-maadi', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract El Tahrir', 'rotaract-el-tahrir', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Heliopolis Sporting', 'rotaract-heliopolis-sporting', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Zayed', 'rotaract-zayed', 'Giza', NULL, 'Egypt', TRUE),
  ('Rotaract Cairo Nile Valley', 'rotaract-cairo-nile-valley', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Cairo Golf Madinaty', 'rotaract-cairo-golf-madinaty', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Kasr El Nile', 'rotaract-kasr-el-nile', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Cairo Fifth Settlement', 'rotaract-cairo-fifth-settlement', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Cairo Heights', 'rotaract-cairo-heights', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Giza El Seid', 'rotaract-giza-el-seid', 'Giza', NULL, 'Egypt', TRUE),
  ('Rotaract Katameya Cairo', 'rotaract-katameya-cairo', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Cairo Sky', 'rotaract-cairo-sky', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Gezira Sporting', 'rotaract-gezira-sporting', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Heliopolis El Tayaran', 'rotaract-heliopolis-el-tayaran', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Cairo-Zamalek', 'rotaract-cairo-zamalek', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Cairo Eagles', 'rotaract-cairo-eagles', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Cairo Royal', 'rotaract-cairo-royal', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Heliopolis El Shorouk', 'rotaract-heliopolis-el-shorouk', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Cairo Platinum', 'rotaract-cairo-platinum', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Cairo', 'rotaract-cairo', 'Cairo', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Rakouda', 'rotaract-alexandria-rakouda', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Renaissance', 'rotaract-alexandria-renaissance', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Sporting', 'rotaract-alexandria-sporting', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract El Nozha United', 'rotaract-el-nozha-united', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Mariout Royal', 'rotaract-alexandria-mariout-royal', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria-West', 'rotaract-alexandria-west', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Sunrise', 'rotaract-alexandria-sunrise', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Pharos Lighthouse', 'rotaract-alexandria-pharos-lighthouse', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Marine', 'rotaract-alexandria-marine', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Cosmopolitan', 'rotaract-alexandria-cosmopolitan', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract San Stefano New Horizon', 'rotaract-san-stefano-new-horizon', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Golden Riders', 'rotaract-alexandria-golden-riders', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Capital', 'rotaract-alexandria-capital', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Renaissance Lumina', 'rotaract-renaissance-lumina', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Sunrise Elite', 'rotaract-sunrise-elite', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract New Alamein Spark', 'rotaract-new-alamein-spark', 'El Alamein', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria San Stefano', 'rotaract-alexandria-san-stefano', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Ramleh', 'rotaract-alexandria-ramleh', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Wave', 'rotaract-alexandria-wave', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Marine Star', 'rotaract-alexandria-marine-star', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract East Griffin', 'rotaract-east-griffin', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria New Era', 'rotaract-alexandria-new-era', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Metropolitan', 'rotaract-alexandria-metropolitan', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract New Alamein Unity', 'rotaract-new-alamein-unity', 'El Alamein', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Renaissance Royal', 'rotaract-alexandria-renaissance-royal', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria', 'rotaract-alexandria', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria Mariout', 'rotaract-alexandria-mariout', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract Alexandria East', 'rotaract-alexandria-east', 'Alexandria', NULL, 'Egypt', TRUE),
  ('Rotaract AAST Alamain', 'rotaract-aast-alamain', 'El Alamein', 'Arab Academy for Science, Technology and Maritime Transport', 'Egypt', TRUE),
  ('Rotaract Damanhour Capital', 'rotaract-damanhour-capital', 'Damanhour', NULL, 'Egypt', TRUE),
  ('Rotaract Damanhour', 'rotaract-damanhour', 'Damanhour', NULL, 'Egypt', TRUE),
  ('Rotaract Fayoum', 'rotaract-fayoum', 'Fayoum', NULL, 'Egypt', TRUE),
  ('Rotaract Red Sea El Gouna', 'rotaract-red-sea-el-gouna', 'El Gouna', NULL, 'Egypt', TRUE),
  ('Rotaract ECU', 'rotaract-ecu', 'Cairo', 'Egyptian Chinese University', 'Egypt', TRUE)
ON CONFLICT (slug) DO NOTHING;
